# Generated by Django 4.2.7 on 2023-11-15 12:10

from django.db import migrations
from django.utils.text import slugify


def generate_service_slugs(apps, schema_editor):
    """
    Generate slugs for existing services.
    """
    Service = apps.get_model('core', 'Service')
    for service in Service.objects.all():
        if not service.slug:
            # Generate a unique slug
            base_slug = slugify(service.title)
            slug = base_slug
            counter = 1
            
            # Check if the slug already exists
            while Service.objects.filter(slug=slug).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
                
            service.slug = slug
            service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_service_slug'),
    ]

    operations = [
        migrations.RunPython(generate_service_slugs, migrations.RunPython.noop),
    ]